apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-server
  template:
    metadata:
      labels:
        app: my-nginx-server
    spec:
      containers:
      - name: my-nginx-server
        image: jaykol/nginx-server:1.0
        ports:
        - containerPort: 80